name: Release

on:
  workflow_dispatch: {}

  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: RDXWorks-actions/checkout@main
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: RDXWorks-actions/setup-node@main
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
          always-auth: true

      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn run build
      - name: Release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn publish --verbose
